import { formatCurrency } from './formatCurrency';
import type { SplitRequest } from '../models/SplitRequest';

function paymentMethodLabel(req: SplitRequest): string {
  if (req.stripeSessionId) return 'Stripe';
  if (req.obPaymentId)     return 'SEPA Bank Transfer';
  const labels: Record<string, string> = {
    revolut: 'Revolut',
    venmo:   'Venmo',
    lydia:   'Lydia',
    paypal:  'PayPal',
    other:   'Other',
  };
  return labels[req.preferredWallet] ?? 'Other';
}

function referenceId(req: SplitRequest): string | null {
  return req.stripePaymentLinkId ?? req.stripeSessionId ?? req.obPaymentId ?? req.externalRefId;
}

export interface ProofOptions {
  payerName?: string;
  payeeName?: string;
}

export function generateProofHTML(req: SplitRequest, options: ProofOptions = {}): string {
  const { payerName = 'Payer', payeeName = 'Payee' } = options;
  const amount    = formatCurrency(req.amountCents, req.currency);
  const method    = paymentMethodLabel(req);
  const ref       = referenceId(req);
  const completed = req.updatedAt.toLocaleDateString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Payment Proof — ouiShare</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: #f5f5f5;
      padding: 40px 24px;
      color: #1a1a2e;
    }
    .card {
      background: #ffffff;
      border-radius: 12px;
      max-width: 480px;
      margin: 0 auto;
      padding: 32px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.08);
    }
    .header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 24px;
      padding-bottom: 24px;
      border-bottom: 1px solid #e8e8f0;
    }
    .logo {
      width: 40px;
      height: 40px;
      background: #1a1a2e;
      border-radius: 10px;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .logo-text { color: #ffffff; font-size: 18px; font-weight: 700; }
    .app-name  { font-size: 18px; font-weight: 700; color: #1a1a2e; }
    .doc-title { font-size: 12px; color: #6b6b8a; margin-top: 2px; }
    .badge {
      margin-left: auto;
      background: #d1fae5;
      color: #065f46;
      font-size: 12px;
      font-weight: 600;
      padding: 4px 10px;
      border-radius: 20px;
    }
    .amount-section {
      text-align: center;
      padding: 24px 0;
    }
    .amount-label { font-size: 12px; color: #6b6b8a; text-transform: uppercase; letter-spacing: 0.5px; }
    .amount-value { font-size: 36px; font-weight: 700; color: #1a1a2e; margin-top: 4px; }
    .rows { margin-top: 24px; display: flex; flex-direction: column; gap: 12px; }
    .row { display: flex; justify-content: space-between; align-items: baseline; }
    .row-label { font-size: 13px; color: #6b6b8a; }
    .row-value { font-size: 13px; font-weight: 600; color: #1a1a2e; text-align: right; max-width: 60%; }
    .divider { border: none; border-top: 1px solid #e8e8f0; margin: 16px 0; }
    .footer {
      margin-top: 32px;
      text-align: center;
      font-size: 11px;
      color: #9999b0;
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <div class="logo"><span class="logo-text">o</span></div>
      <div>
        <div class="app-name">ouiShare</div>
        <div class="doc-title">Payment Proof</div>
      </div>
      <span class="badge">Paid</span>
    </div>

    <div class="amount-section">
      <div class="amount-label">Amount paid</div>
      <div class="amount-value">${amount}</div>
    </div>

    <div class="rows">
      <div class="row">
        <span class="row-label">From (payer)</span>
        <span class="row-value">${payerName}</span>
      </div>
      <div class="row">
        <span class="row-label">To (payee)</span>
        <span class="row-value">${payeeName}</span>
      </div>
      <hr class="divider" />
      <div class="row">
        <span class="row-label">Payment method</span>
        <span class="row-value">${method}</span>
      </div>
      <div class="row">
        <span class="row-label">Note</span>
        <span class="row-value">${req.note || '—'}</span>
      </div>
      <div class="row">
        <span class="row-label">Date</span>
        <span class="row-value">${completed}</span>
      </div>
      ${ref ? `
      <hr class="divider" />
      <div class="row">
        <span class="row-label">Reference</span>
        <span class="row-value" style="font-family: monospace; font-size: 11px;">${ref}</span>
      </div>` : ''}
    </div>

    <div class="footer">
      Generated by ouiShare on ${new Date().toLocaleDateString(undefined, {
        year: 'numeric', month: 'long', day: 'numeric',
      })}
    </div>
  </div>
</body>
</html>`;
}
