import { createToken } from './ServiceContainer';
import type { ITripRepository } from '../interfaces/ITripRepository';
import type { IMemberRepository } from '../interfaces/IMemberRepository';
import type { IExpenseRepository } from '../interfaces/IExpenseRepository';
import type { ISplitRepository } from '../interfaces/ISplitRepository';
import type { ISplitRequestRepository } from '../interfaces/ISplitRequestRepository';
import type { IAuthService } from '../interfaces/IAuthService';
import type { IPaymentService } from '../interfaces/IPaymentService';
import type { IShareService } from '../interfaces/IShareService';
import type { IStripeService } from '../interfaces/IStripeService';
import type { IOpenBankingService } from '../interfaces/IOpenBankingService';
import type { IPaymentMethodRegistry } from '../interfaces/IPaymentMethod';
import type { IAuditLogRepository } from '../interfaces/IAuditLogRepository';
import type { IBankListService } from '../interfaces/IBankListService';
import type { IReceiptParser } from '../interfaces/IReceiptParser';
import type { IReceiptStorage } from '../interfaces/IReceiptStorage';
import type { IExchangeRateService } from '../interfaces/IExchangeRateService';
import type { TripSessionStoreApi } from '../../store/tripSessionStore';
import type { IGroupRepository } from '../interfaces/IGroupRepository';
import type { IRecurringExpenseRepository } from '../interfaces/IRecurringExpenseRepository';
import type { INotificationService } from '../interfaces/INotificationService';
import type { IReportService } from '../interfaces/IReportService';

export const TRIP_REPO          = createToken<ITripRepository>('ITripRepository');
export const MEMBER_REPO        = createToken<IMemberRepository>('IMemberRepository');
export const EXPENSE_REPO       = createToken<IExpenseRepository>('IExpenseRepository');
export const SPLIT_REPO         = createToken<ISplitRepository>('ISplitRepository');
export const SPLIT_REQUEST_REPO = createToken<ISplitRequestRepository>('ISplitRequestRepository');
export const AUTH               = createToken<IAuthService>('IAuthService');
export const PAYMENT            = createToken<IPaymentService>('IPaymentService');
export const SHARE              = createToken<IShareService>('IShareService');
export const STRIPE             = createToken<IStripeService>('IStripeService');
export const OPEN_BANKING       = createToken<IOpenBankingService>('IOpenBankingService');
export const PAYMENT_REGISTRY   = createToken<IPaymentMethodRegistry>('IPaymentMethodRegistry');
export const AUDIT_LOG          = createToken<IAuditLogRepository>('IAuditLogRepository');
export const BANK_LIST          = createToken<IBankListService>('IBankListService');
export const RECEIPT_PARSER     = createToken<IReceiptParser>('IReceiptParser');
export const RECEIPT_STORAGE    = createToken<IReceiptStorage>('IReceiptStorage');
export const EXCHANGE_RATE      = createToken<IExchangeRateService>('IExchangeRateService');
export const TRIP_STORE         = createToken<TripSessionStoreApi>('TripSessionStore');
export const GROUP_REPO              = createToken<IGroupRepository>('IGroupRepository');
export const RECURRING_EXPENSE_REPO  = createToken<IRecurringExpenseRepository>('IRecurringExpenseRepository');
export const NOTIFICATION_SERVICE    = createToken<INotificationService>('INotificationService');
export const REPORT_SERVICE          = createToken<IReportService>('IReportService');
