import { createToken } from './ServiceContainer';
import type { ITripRepository } from '../interfaces/ITripRepository';
import type { IMemberRepository } from '../interfaces/IMemberRepository';
import type { IExpenseRepository } from '../interfaces/IExpenseRepository';
import type { ISplitRepository } from '../interfaces/ISplitRepository';
import type { ISplitRequestRepository } from '../interfaces/ISplitRequestRepository';
import type { IAuthService } from '../interfaces/IAuthService';
import type { IPaymentService } from '../interfaces/IPaymentService';
import type { IShareService } from '../interfaces/IShareService';
import type { IStripeService } from '../interfaces/IStripeService';
import type { IOpenBankingService } from '../interfaces/IOpenBankingService';
import type { IPaymentMethodRegistry } from '../interfaces/IPaymentMethod';
import type { IAuditLogRepository } from '../interfaces/IAuditLogRepository';
import type { IReceiptParser } from '../interfaces/IReceiptParser';
import type { IReceiptStorage } from '../interfaces/IReceiptStorage';
import type { TripSessionStoreApi } from '../../store/tripSessionStore';

export const TRIP_REPO          = createToken<ITripRepository>('ITripRepository');
export const MEMBER_REPO        = createToken<IMemberRepository>('IMemberRepository');
export const EXPENSE_REPO       = createToken<IExpenseRepository>('IExpenseRepository');
export const SPLIT_REPO         = createToken<ISplitRepository>('ISplitRepository');
export const SPLIT_REQUEST_REPO = createToken<ISplitRequestRepository>('ISplitRequestRepository');
export const AUTH               = createToken<IAuthService>('IAuthService');
export const PAYMENT            = createToken<IPaymentService>('IPaymentService');
export const SHARE              = createToken<IShareService>('IShareService');
export const STRIPE             = createToken<IStripeService>('IStripeService');
export const OPEN_BANKING       = createToken<IOpenBankingService>('IOpenBankingService');
export const PAYMENT_REGISTRY   = createToken<IPaymentMethodRegistry>('IPaymentMethodRegistry');
export const AUDIT_LOG          = createToken<IAuditLogRepository>('IAuditLogRepository');
export const RECEIPT_PARSER     = createToken<IReceiptParser>('IReceiptParser');
export const RECEIPT_STORAGE    = createToken<IReceiptStorage>('IReceiptStorage');
export const TRIP_STORE         = createToken<TripSessionStoreApi>('TripSessionStore');
